update actions with custom get-changes

diff --git a/.github/workflows/validate-models.yml b/.github/workflows/validate-models.yml
--- a/.github/workflows/validate-models.yml
+++ b/.github/workflows/validate-models.yml
@@ -4,8 +4,7 @@ on:
   pull_request:
     branches: [main]
     paths:
-      - 'dtmi/**'
-
+      - '**/*'
 jobs:
   validate-models:
     runs-on: ubuntu-latest
@@ -14,7 +13,7 @@ jobs:
         uses: actions/checkout@v2
 
       - id: files
-        uses: jitterbit/get-changed-files@v1
+        uses: digimaun/get-changed-files@v2
 
       - name: Configure GitHub feed
         run: dotnet nuget add source https://nuget.pkg.github.com/Azure/index.json -n github -u Azure -p ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text
@@ -26,7 +25,7 @@ jobs:
         run: |
           for f in  ${{ steps.files.outputs.added_modified }};
           do
-              if [[ $f == *"dtmi/"* ]]
+              if [[ $f =~ ^dtmi([\/\\][a-z0-9_]+){2,}-([1-9][0-9]{0,8}).json$ ]]
               then
                   echo "validating $f"
                   dmr-client validate --model-file $f --repository $PWD
@@ -34,11 +33,101 @@ jobs:
                   then
                       echo "validation ok: $f"
                   else
-                      echo "error validating model"
-                      exit 1
+                      echo "error validating model: $f"
+                      exit $?
                   fi
               else
                 echo "skipping $f"
               fi
           done
+        shell: bash
+  reject-edits:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - id: files
+        uses: digimaun/get-changed-files@v2
+
+      - name: Reject edits to Models
+        run: |
+          exit_code=0
+          for f in  ${{ steps.files.outputs.modified }};
+          do
+            if [[ $f =~ ^dtmi([\/\\][a-z0-9_]+){2,}-([1-9][0-9]{0,8}).json$ ]]
+            then
+              echo "edits aren't allowed to existing DTDL files: $f"
+              exit_code=1
+            fi
+          done
+          exit $exit_code
+        shell: bash
+  reject-renames:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - id: files
+        uses: digimaun/get-changed-files@v2
+
+      - name: Reject renames to Models
+        run: |
+          exit_code=0
+          for f in  ${{ steps.files.outputs.renamed }};
+          do
+            if [[ $f =~ ^dtmi([\/\\][a-z0-9_]+){2,}-([1-9][0-9]{0,8}).json$ ]]
+            then
+              echo "renames aren't allowed to existing DTDL files: $f"
+              exit_code=1
+            fi
+          done
+          exit $exit_code
+        shell: bash
+  reject-deletions:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - id: files
+        uses: digimaun/get-changed-files@v2
+
+      - name: Reject deletions to Models
+        run: |
+          exit_code=0
+          for f in  ${{ steps.files.outputs.removed }};
+          do
+            if [[ $f =~ ^dtmi([\/\\][a-z0-9_]+){2,}-([1-9][0-9]{0,8}).json$ ]]
+            then
+              echo "deletions aren't allowed to existing DTDL files: $f"
+              exit_code=1
+            fi
+          done
+          exit $exit_code
+        shell: bash
+  reject-non-models:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - id: files
+        uses: digimaun/get-changed-files@v2
+
+      - name: Reject deletions to Models
+        run: |
+          exit_code=0
+          for f in  ${{ steps.files.outputs.added_modified }};
+          do
+              if [[ $f =~ ^dtmi([\/\\][a-z0-9_]+){2,}-([1-9][0-9]{0,8}).json$ ]]
+              then
+                  echo "skipping DTDL file $f"
+              else
+                echo "edits made to non-DTDL files is not allowed: $f"
+                exit_code=1
+              fi
+          done
+          exit $exit_code
         shell: bash
